배포시 에러나..
useSearchParams() should be wrapped in a suspense boundary at page "/ai-analysis". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at s (/vercel/path0/.next/server/chunks/509.js:3:85112)
    at d (/vercel/path0/.next/server/chunks/509.js:25:101832)
    at A (/vercel/path0/.next/server/app/ai-analysis/page.js:5:8900)
    at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nq (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nU (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
Error occurred prerendering page "/ai-analysis". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /ai-analysis/page: /ai-analysis, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1